# Generated by Django 2.1.1 on 2018-10-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181005_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='EmailAddress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ProfileText',
        ),
    ]
