# Generated by Django 2.1.2 on 2018-10-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181005_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='EmailAddress',
            field=models.EmailField(default='defaultemail@gmail.com', max_length=180),
        ),
    ]
