# Generated by Django 2.1.2 on 2018-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181005_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Location',
            field=models.CharField(default='homeless', max_length=200),
        ),
    ]
