# Generated by Django 2.1.1 on 2018-10-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181005_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availability', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Friends',
            field=models.ManyToManyField(blank=True, default='none', related_name='_profile_Friends_+', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Availability',
            field=models.ManyToManyField(default='None', to='api.Availability'),
        ),
    ]
