# Generated by Django 2.1.1 on 2018-10-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181012_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='api.Profile'),
        ),
    ]
