# Generated by Django 2.1.1 on 2018-10-12 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20181012_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='user',
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
