# Generated by Django 2.1.1 on 2018-10-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181012_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='Availability',
            field=models.DateField(),
        ),
    ]
