# Generated by Django 2.1.1 on 2018-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181012_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='midpoint',
            field=models.TextField(default=''),
        ),
    ]
