# Generated by Django 2.1.1 on 2018-10-23 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181022_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='VoteOption',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='userid',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='latLong',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='LatLong',
            new_name='latLong',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='LocationText',
            new_name='locationName',
        ),
        migrations.RemoveField(
            model_name='location',
            name='url',
        ),
        migrations.AddField(
            model_name='location',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
        migrations.AddField(
            model_name='location',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='location',
            name='types',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
