# Generated by Django 2.1.1 on 2018-10-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181023_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.RemoveField(
            model_name='eventinvitation',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='reminder',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='EventId',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='location',
            name='event',
        ),
        migrations.AddField(
            model_name='location',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventInvitation',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
