# Generated by Django 2.1.1 on 2018-10-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181024_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coordinates',
            field=models.CharField(default='0,0', max_length=200, null=True),
        ),
    ]
