# Generated by Django 2.1.1 on 2018-10-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coordinates',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
    ]
